version: '3.8'
services:
  api:
    build: .
    image: my-node-app
    container_name: my-node-api
    ports:
      - "7000:7000"
    environment:
      - ELASTIC_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - esnet

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: my-elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - esnet

volumes:
  esdata:
networks:
  esnet: 